
name: Build and Push Docker Image to Docker Hub

on:
  workflow_call:  # entry point for the workflow call event
    inputs:
      branch:
        required: false
        type: string
        default: main
      build_command:
        required: false
        type: string
        default: mvn clean package
      dockerfile_path:
        required: true
        type: string
      docker_tags:
        required: false
        type: string
        default: latest
      push_image:
        required: false
        type: boolean
        default: true
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true    


jobs:
  template-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build with Maven
      run: ${{ inputs.build_command }}  #Build project, default command is "mvn clean package" (incoming parameter)

    - name: Extract Maven project version
      id: extract_version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Print Version
      run: echo Project version=$VERSION

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}

    - name: Build and push Docker image
      if: ${{ inputs.push_image == 'true' }} 
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ inputs.dockerfile_path }}  #path to Dockerfile (incoming parameter)
        push: true
        tags: |
          ${{ secrets.docker_username }}/qubership-integration-engine:${{ env.VERSION }}