name: Publish Java package to Github Packages

on: 
  workflow_call:
    inputs:
      maven_profile:
        required: false
        type: string
        default: "github"
      maven_server_id:
        required: false
        type: string
        default: "github"
      artifact_version:
        required: false
        type: string
        default: ''

    secrets:
      maven_gpg_passphrase:
        required: true
      maven_gpg_private_key:
        required: true
      github_repo_token:
        required: true
permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ${{ maven_server_id }}
          server-password: GITHUB_TOKEN
          gpg-private-key: ${{ secrets.maven_gpg_private_key }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish package default versioning
        if: ${{ artifact_version == '' }}
        run: |
          mvn -B org.codehaus.mojo:build-helper-maven-plugin:3.6.0:parse-version org.codehaus.mojo:versions-maven-plugin:2.17.1:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}+${{ github.run_number }}
          mvn -B -P${{ maven_profile }} deploy
        env:
          GITHUB_TOKEN: ${{ secrets.github_repo_token }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.maven_gpg_passphrase }}

      - name: Publish package provided version
        if: ${{ ! artifact_version == '' }}
        run: |
          mvn -B org.codehaus.mojo:build-helper-maven-plugin:3.6.0:parse-version org.codehaus.mojo:versions-maven-plugin:2.17.1:set -DnewVersion=${{ artifact_version }}
          mvn -B -P${{ maven_profile }} deploy
        env:
          GITHUB_TOKEN: ${{ secrets.github_repo_token }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.maven_gpg_passphrase }}
