name: Docker Tag Template

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug GITHUB_REF
        run: echo "GITHUB_REF = $GITHUB_REF"

      - name: Set docker tags variable
        id: set_tags
        run: |
          TAG=$(echo "${GITHUB_REF}" | sed -e 's|refs/tags/||' -e 's|refs/heads/||')
          if [ -z "$TAG" ]; then TAG="main"; fi
          echo "docker_tags=$TAG"
          echo "::set-output name=docker_tags::$TAG"

    outputs:
      docker_tags: ${{ steps.set_tags.outputs.docker_tags }}
