name: Docker Tag Template

on:
  workflow_call:
    outputs:
      docker_tags:
        value: ${{ jobs.tag.outputs.docker_tags }}

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      docker_tags: ${{ steps.set_tags.outputs.docker_tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug GITHUB_REF
        run: echo "GITHUB_REF = $GITHUB_REF"

      - name: Set docker tags variable
        id: set_tags
        run: |
          TAG=$(echo "${GITHUB_REF}" | sed -e 's|refs/tags/||' -e 's|refs/heads/||')
          if [ -z "$TAG" ]; then TAG="main"; fi
          echo "docker_tags=$TAG" >> $GITHUB_OUTPUT

      - name: Debug docker_tags
        run: echo "docker_tags = ${{ steps.set_tags.outputs.docker_tags }}"
